services:
  backend:
    build: ./backend
    container_name: opsboard-backend
    environment:
      - DATABASE_URL=postgresql://postgres:Ritom100@host.docker.internal:5433/opsboard
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: opsboard-frontend
    ports:
      - "3000:80"